name: Allocation Data Transfer
run-name: Transfer Allocation Data from ${{ inputs.sourceRealmName }} to ${{ inputs.targetRealmName }}
on:
  workflow_dispatch:
    inputs:
      sourceRealmName:
        type: string
        description: Name of the source LIAM Realm
        required: true
      sourceRealmId:
        type: string
        description: ID of the source LIAM Realm
        required: true
      targetRealmName:
        type: string
        description: Name of the target LIAM Realm
        required: true
      targetRealmId:
        type: string
        description: ID of the target LIAM Realm
        required: true
      geography:
        type: string
        description: Environment Deployment Zone(eg. us, eu, apac)
        required: true
      size:
        type: string
        description: Environment Size(eg. Dev)
        required: true
      jpowerId:
        required: true
        type: string
        description: JPowerID
      customerId:
        required: true
        type: string
        description: Realm Customer ID
      envType:
        required: true
        description: Environment Type (Demo⇒pldena,PSR⇒pltpsr,Pilot⇒plpprvna,Non-Prod⇒plpstgna,Prod⇒plp##,Dev⇒pltna)
        type: choice
        default: Dev
        options:
          - Demo
          - PSR
          - Pilot
          - Non-Prod
          - Prod
          - Dev
      keyVaultURL:
        required: true
        type: string
        description: Key Vault URL to get Client Credential
        default: "https://o67wh6yaleseujavasbb39k7.vault.azure.net"
      planningInstanceId:
        required: false
        type: string
        description: Optional Planning Instance ID for ondemand data source
        default: ""
      startingStepName:
        required: false
        type: string
        description: Optional Name of the step where the workflow needs to be started.
        default: NONE

  workflow_call:
    inputs:
      sourceRealmName:
        type: string
        description: Name of the source LIAM Realm
        required: true
      sourceRealmId:
        type: string
        description: ID of the source LIAM Realm
        required: true
      targetRealmName:
        type: string
        description: Name of the target LIAM Realm
        required: true
      targetRealmId:
        type: string
        description: ID of the target LIAM Realm
        required: true
      geography:
        type: string
        description: Environment Deployment Zone
        required: true
      size:
        type: string
        description: Environment Size
        required: true
      jpowerId:
        required: true
        type: string
        description: JPowerID
      customerId:
        required: true
        type: string
        description: Realm Customer ID
      envType:
        required: true
        type: string
        description: Environment Type
      keyVaultURL:
        required: true
        type: string
        description: Key Vault URL to get Client Credential
      planningInstanceId:
        required: false
        type: string
        description: Optional Planning Instance ID for ondemand data source
        default: ""
      startingStepName:
        required: false
        type: string
        description: Optional Name of the step where the workflow needs to be started.
        default: NONE

defaults:
  run:
    shell: pwsh
jobs:
  get_by_env:
    runs-on: ubuntu-latest
    outputs:
      byenv: ${{ steps.get_by_env.outputs.byenv }}
    steps:
      - name: Get BY Env
        id: get_by_env
        uses: ./.github/actions/get_by_env
        with:
          geography: ${{ inputs.geography }}
          envType: ${{ inputs.envType }}
      - name: Echo Output
        id: echo_output
        run: |
          Write-Output ${{ steps.get_by_env.outputs.byenv }}

  transfer_allocation_data:
    runs-on: ubuntu-latest
    needs: get_by_env
    environment: ${{ needs.get_by_env.outputs.byenv }}
    steps:
      - name: Echo Input
        id: echo_input
        run: |
          Write-Output "sourceRealmName: [${{ inputs.sourceRealmName }}]"
          Write-Output "sourceRealmId: [${{ inputs.sourceRealmId }}]"
          Write-Output "targetRealmName: [${{ inputs.targetRealmName }}]"
          Write-Output "targetRealmId: [${{ inputs.targetRealmId }}]"
          Write-Output "geography: [${{ inputs.geography }}]"
          Write-Output "envType: [${{ inputs.envType }}]"
          Write-Output "size: [${{ inputs.size }}]"
          Write-Output "costCenter: [474000]"
          Write-Output "jpowerId: [${{ inputs.jpowerId }}]"
          Write-Output "customerId: [${{ inputs.customerId }}]"
          Write-Output "Key Vault Name: [${{ inputs.keyVaultURL }}]"
          Write-Output "Planning Instance ID: [${{ inputs.planningInstanceId }}]"
          Write-Output "Starting Step Name: [${{ inputs.startingStepName }}]"

      - name: Invoke Get Starting Step
        id: get_step_value
        uses: ./.github/actions/get_starting_step
        with:
          starting_step_name: ${{ inputs.startingStepName }}

      - name: Check out repository code
        uses: actions/checkout@v4.1.1

      - name: Setting up BY Script
        uses: ./.github/actions/setup_by_script

      - name: Create Source Realm Credential
        uses: ./.github/actions/apply_aep_parameter
        with:
          stratosphere_client_id: ${{ secrets.SX_CBP_DEVOPS_CLIENT_ID }}
          stratosphere_client_secret: ${{ secrets.SX_CBP_DEVOPS_CLIENT_SECRET }}
          realm_name: ${{ inputs.sourceRealmName }}
          realm_id: ${{ inputs.sourceRealmId }}
          customer_id: ${{ inputs.customerId }}
          jpower_id: ${{ inputs.jpowerId }}
          env_type: ${{ inputs.envType }}
          geography: ${{ inputs.geography }}
          size: ${{ inputs.size }}
          costCenter: 474000
          by_env: ${{ needs.get_by_env.outputs.byenv }}
          key_vault_url: ${{ inputs.keyVaultURL }}
          alt_key_vault_name: ${{ vars.SX_CBP_DEVOPS_KV_NAME }}
          stratosphere_api_url: ${{ vars.STRATOSPHERE_API_URL }}
          stratosphere_auth_url: ${{ vars.STRATOSPHERE_AUTH_URL }}
          output_file: source_realm_credential.json

      - name: Create Target Realm Credential
        uses: ./.github/actions/apply_aep_parameter
        with:
          stratosphere_client_id: ${{ secrets.SX_CBP_DEVOPS_CLIENT_ID }}
          stratosphere_client_secret: ${{ secrets.SX_CBP_DEVOPS_CLIENT_SECRET }}
          realm_name: ${{ inputs.targetRealmName }}
          realm_id: ${{ inputs.targetRealmId }}
          customer_id: ${{ inputs.customerId }}
          jpower_id: ${{ inputs.jpowerId }}
          env_type: ${{ inputs.envType }}
          geography: ${{ inputs.geography }}
          size: ${{ inputs.size }}
          costCenter: 474000
          by_env: ${{ needs.get_by_env.outputs.byenv }}
          key_vault_url: ${{ inputs.keyVaultURL }}
          alt_key_vault_name: ${{ vars.SX_CBP_DEVOPS_KV_NAME }}
          stratosphere_api_url: ${{ vars.STRATOSPHERE_API_URL }}
          stratosphere_auth_url: ${{ vars.STRATOSPHERE_AUTH_URL }}
          output_file: target_realm_credential.json

      - name: Check out Realm Repository
        uses: ./.github/actions/checkout_realm_repository
        with:
          automation_token: ${{ secrets.AUTOMATION_PAT_TOKEN }}

      - name: Setup Source Realm Folder
        id: setup_source_realm_folder
        run: |
          New-Item -Force -Path ${{ github.workspace }} -Name 'realms/${{ inputs.sourceRealmName }}/realm_info' -Type Directory 
          Get-ChildItem ${{ github.workspace }}
          Copy-Item -Force -Verbose realm_${{ inputs.sourceRealmName }}_info.json -Destination ${{ github.workspace }}/realms/${{ inputs.sourceRealmName }}/realm_info/realm_info.json

      - name: Setup Target Realm Folder
        id: setup_target_realm_folder
        run: |
          New-Item -Force -Path ${{ github.workspace }} -Name 'realms/${{ inputs.targetRealmName }}/realm_info' -Type Directory 
          Get-ChildItem ${{ github.workspace }}
          Copy-Item -Force -Verbose realm_${{ inputs.targetRealmName }}_info.json -Destination ${{ github.workspace }}/realms/${{ inputs.targetRealmName }}/realm_info/realm_info.json

      - name: Create Credential Files
        uses: ./.github/actions/setup_credential_files
        with:
          realm_credential: ${{ secrets.LIAM_CREDENTIAL }}
          snowflake_environment: ${{ secrets.SF_CONTEXT }}
          snowflake_private_key: ${{ secrets.SF_RSA_KEY }}

      - name: Export Allocation Data
        id: export_allocation_data
        uses: ./.github/actions/export_allocation_data
        with:
          source_realm_name: ${{ inputs.sourceRealmName }}
          source_realm_credential_path: source_realm_credential.json
          output_folder: allocation_data

      - name: Import Allocation Data
        id: import_allocation_data
        uses: ./.github/actions/import_allocation_data
        with:
          target_realm_name: ${{ inputs.targetRealmName }}
          target_realm_credential_path: target_realm_credential.json
          input_file: allocation_data/exported_allocation_data.zip
          planning_instance_id: ${{ inputs.planningInstanceId }}

      - name: Upload Exported Data as Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: allocation_data
          path: |
            ${{ github.workspace }}/allocation_data
          overwrite: true
          retention-days: 30
