name: Allocation Data Transfer
run-name: Transfer Allocation Data from ${{ inputs.source_realm_name }} to ${{ inputs.target_realm_name }}
on:
  workflow_dispatch:
    inputs:
      source_realm_name:
        type: string
        description: Name of the source LIAM Realm
        required: true
      source_realm_id:
        type: string
        description: ID of the source LIAM Realm
        required: true
      target_realm_name:
        type: string
        description: Name of the target LIAM Realm
        required: true
      target_realm_id:
        type: string
        description: ID of the target LIAM Realm
        required: true
      geography:
        type: string
        description: Environment Deployment Zone(eg. us, eu, apac)
        required: true
      size:
        type: string
        description: Environment Size(eg. Dev)
        required: true
      jpowerId:
        required: true
        type: string
        description: JPowerID
      customerId:
        required: true
        type: string
        description: Realm Customer ID
      envType:
        required: true
        description: Environment Type (Demo⇒pldena,PSR⇒pltpsr,Pilot⇒plpprvna,Non-Prod⇒plpstgna,Prod⇒plp##,Dev⇒pltna)
        type: choice
        default: Dev
        options:
          - Demo
          - PSR
          - Pilot
          - Non-Prod
          - Prod
          - Dev
      keyVaultURL:
        required: true
        type: string
        description: Key Vault URL to get Client Credential
        default: "https://o67wh6yaleseujavasbb39k7.vault.azure.net"
      planningInstanceId:
        required: false
        type: string
        description: Planning Instance ID (required for certain operations)
        default: ""

defaults:
  run:
    shell: pwsh

jobs:
  get_by_env:
    runs-on: ubuntu-latest
    outputs:
      byenv: ${{ steps.get_by_env.outputs.byenv }}
    steps:
      - name: Get BY Env
        id: get_by_env
        uses: BY-Product-Development/plan-abp-automation/.github/actions/get_by_env@gha-latest
        with:
          geography: ${{ inputs.geography }}
          envType: ${{ inputs.envType }}
      - name: Echo Output
        id: echo_output
        run: |
          Write-Output ${{ steps.get_by_env.outputs.byenv }}

  transfer_allocation_data:
    runs-on: ubuntu-latest
    needs: get_by_env
    environment: ${{ needs.get_by_env.outputs.byenv }}
    steps:
      - name: Echo Input
        id: echo_input
        run: |
          Write-Output "Source Realm Name: [${{ inputs.source_realm_name }}]"
          Write-Output "Source Realm ID: [${{ inputs.source_realm_id }}]"
          Write-Output "Target Realm Name: [${{ inputs.target_realm_name }}]"
          Write-Output "Target Realm ID: [${{ inputs.target_realm_id }}]"
          Write-Output "Geography: [${{ inputs.geography }}]"
          Write-Output "Environment Type: [${{ inputs.envType }}]"
          Write-Output "Size: [${{ inputs.size }}]"
          Write-Output "JPower ID: [${{ inputs.jpowerId }}]"
          Write-Output "Customer ID: [${{ inputs.customerId }}]"
          Write-Output "Key Vault URL: [${{ inputs.keyVaultURL }}]"
          Write-Output "Planning Instance ID: [${{ inputs.planningInstanceId }}]"

      - name: Check out repository code
        uses: actions/checkout@v4.1.1

      - name: Setting up BY Script
        uses: BY-Product-Development/plan-abp-automation/.github/actions/setup_by_script@gha-latest

      - name: Create Source Realm Credential
        uses: BY-Product-Development/plan-abp-automation/.github/actions/apply_aep_parameter@gha-latest
        with:
          stratosphere_client_id: ${{ secrets.SX_CBP_DEVOPS_CLIENT_ID }}
          stratosphere_client_secret: ${{ secrets.SX_CBP_DEVOPS_CLIENT_SECRET }}
          realm_name: ${{ inputs.source_realm_name }}
          realm_id: ${{ inputs.source_realm_id }}
          customer_id: ${{ inputs.customerId }}
          jpower_id: ${{ inputs.jpowerId }}
          env_type: ${{ inputs.envType }}
          geography: ${{ inputs.geography }}
          size: ${{ inputs.size }}
          costCenter: 474000
          by_env: ${{ needs.get_by_env.outputs.byenv }}
          key_vault_url: ${{ inputs.keyVaultURL }}
          alt_key_vault_name: ${{ vars.SX_CBP_DEVOPS_KV_NAME }}
          stratosphere_api_url: ${{ vars.STRATOSPHERE_API_URL }}
          stratosphere_auth_url: ${{ vars.STRATOSPHERE_AUTH_URL }}

      - name: Check out Realm Repository
        uses: BY-Product-Development/plan-abp-automation/.github/actions/checkout_realm_repository@gha-latest
        with:
          automation_token: ${{ secrets.AUTOMATION_PAT_TOKEN }}

      - name: Setup Source Realm Folder
        id: setup_source_realm_folder
        run: |
          New-Item -Force -Path ${{ github.workspace }} -Name 'realms/${{ inputs.source_realm_name }}/realm_info' -Type Directory 
          Get-ChildItem ${{ github.workspace }}
          Copy-Item -Force -Verbose realm_${{ inputs.source_realm_name }}_info.json -Destination ${{ github.workspace }}/realms/${{ inputs.source_realm_name }}/realm_info/realm_info.json

      - name: Create Source Realm Credential Files
        uses: BY-Product-Development/plan-abp-automation/.github/actions/setup_credential_files@gha-latest
        with:
          realm_credential: ${{ secrets.LIAM_CREDENTIAL }}
          snowflake_environment: ${{ secrets.SF_CONTEXT }}
          snowflake_private_key: ${{ secrets.SF_RSA_KEY }}

      # Create folder for exported data
      - name: Create Export Directory
        run: |
          New-Item -Force -Path ${{ github.workspace }} -Name 'allocation_export' -Type Directory

      # Export allocation data from source realm
      - name: Export Allocation Data
        id: export_allocation_data
        run: |
          # Get authentication token from source realm credential
          $realmCredential = Get-Content -Path ${{ inputs.source_realm_name }}.postman_environment.json | ConvertFrom-Json
          $realmInfo = Get-Content -Path ${{ github.workspace }}/realms/${{ inputs.source_realm_name }}/realm_info/realm_info.json | ConvertFrom-Json
          
          # Extract base URL from realm info
          $baseUrl = $realmInfo.baseUrl
          
          # Extract bearer token from realm credential
          $bearerToken = $realmCredential.values | Where-Object { $_.key -eq "accessToken" } | Select-Object -ExpandProperty value
          
          # Set headers for API call
          $headers = @{
            "Authorization" = "Bearer $bearerToken"
            "Content-Type" = "application/json"
          }
          
          # Add planningInstanceId to headers if provided
          if (-not [string]::IsNullOrEmpty('${{ inputs.planningInstanceId }}')) {
            $headers.Add("planningInstanceId", "${{ inputs.planningInstanceId }}")
            $headers.Add("identity-context", "${{ inputs.planningInstanceId }}")
          }
          
          # Make the export API call
          $exportUrl = "$baseUrl/api/v1/allocation/export-db-records"
          $exportOutputPath = "${{ github.workspace }}/allocation_export/exported-data.zip"
          
          Write-Output "Exporting allocation data from $exportUrl"
          Invoke-WebRequest -Uri $exportUrl -Headers $headers -Method GET -OutFile $exportOutputPath
          
          if (Test-Path $exportOutputPath) {
            Write-Output "Successfully exported allocation data to $exportOutputPath"
          } else {
            throw "Failed to export allocation data"
          }

      # Create target realm credential
      - name: Create Target Realm Credential
        id: create_target_realm_credential
        run: |
          # Rename the source realm credential file temporarily
          if (Test-Path "${{ inputs.source_realm_name }}.postman_environment.json") {
            Rename-Item -Path "${{ inputs.source_realm_name }}.postman_environment.json" -NewName "source_realm_credential.json"
          }

      - name: Apply Target Realm Parameters
        uses: BY-Product-Development/plan-abp-automation/.github/actions/apply_aep_parameter@gha-latest
        with:
          stratosphere_client_id: ${{ secrets.SX_CBP_DEVOPS_CLIENT_ID }}
          stratosphere_client_secret: ${{ secrets.SX_CBP_DEVOPS_CLIENT_SECRET }}
          realm_name: ${{ inputs.target_realm_name }}
          realm_id: ${{ inputs.target_realm_id }}
          customer_id: ${{ inputs.customerId }}
          jpower_id: ${{ inputs.jpowerId }}
          env_type: ${{ inputs.envType }}
          geography: ${{ inputs.geography }}
          size: ${{ inputs.size }}
          costCenter: 474000
          by_env: ${{ needs.get_by_env.outputs.byenv }}
          key_vault_url: ${{ inputs.keyVaultURL }}
          alt_key_vault_name: ${{ vars.SX_CBP_DEVOPS_KV_NAME }}
          stratosphere_api_url: ${{ vars.STRATOSPHERE_API_URL }}
          stratosphere_auth_url: ${{ vars.STRATOSPHERE_AUTH_URL }}

      - name: Setup Target Realm Folder
        id: setup_target_realm_folder
        run: |
          New-Item -Force -Path ${{ github.workspace }} -Name 'realms/${{ inputs.target_realm_name }}/realm_info' -Type Directory 
          Copy-Item -Force -Verbose realm_${{ inputs.target_realm_name }}_info.json -Destination ${{ github.workspace }}/realms/${{ inputs.target_realm_name }}/realm_info/realm_info.json

      # Import allocation data to target realm
      - name: Import Allocation Data
        id: import_allocation_data
        run: |
          # Get authentication token from target realm credential
          $realmCredential = Get-Content -Path ${{ inputs.target_realm_name }}.postman_environment.json | ConvertFrom-Json
          $realmInfo = Get-Content -Path ${{ github.workspace }}/realms/${{ inputs.target_realm_name }}/realm_info/realm_info.json | ConvertFrom-Json
          
          # Extract base URL from realm info
          $baseUrl = $realmInfo.baseUrl
          
          # Extract bearer token from realm credential
          $bearerToken = $realmCredential.values | Where-Object { $_.key -eq "accessToken" } | Select-Object -ExpandProperty value
          
          # Set headers for API call
          $headers = @{
            "Authorization" = "Bearer $bearerToken"
            "Content-Type" = "multipart/form-data"
          }
          
          # Add planningInstanceId to headers if provided
          if (-not [string]::IsNullOrEmpty('${{ inputs.planningInstanceId }}')) {
            $headers.Add("planningInstanceId", "${{ inputs.planningInstanceId }}")
            $headers.Add("identity-context", "${{ inputs.planningInstanceId }}")
          }
          
          # Make the import API call
          $importUrl = "$baseUrl/api/v1/allocation/import-db-records"
          $importFilePath = "${{ github.workspace }}/allocation_export/exported-data.zip"
          
          Write-Output "Importing allocation data to $importUrl"
          
          # Using curl to handle multipart/form-data properly
          $curlCommand = @"
          curl -X POST "$importUrl" \
          -H "Authorization: Bearer $bearerToken" \
          -F "file=@$importFilePath"
          "@
          
          if (-not [string]::IsNullOrEmpty('${{ inputs.planningInstanceId }}')) {
            $curlCommand += ' -H "planningInstanceId: ${{ inputs.planningInstanceId }}" -H "identity-context: ${{ inputs.planningInstanceId }}"'
          }
          
          Write-Output "Executing curl command for import"
          Invoke-Expression -Command $curlCommand
          
          if ($LASTEXITCODE -ne 0) {
            throw "Failed to import allocation data with exit code $LASTEXITCODE"
          } else {
            Write-Output "Successfully imported allocation data"
          }

      # Restore source realm credential for cleanup
      - name: Restore Source Realm Credential
        id: restore_source_credential
        run: |
          if (Test-Path "source_realm_credential.json") {
            Rename-Item -Path "source_realm_credential.json" -NewName "${{ inputs.source_realm_name }}.postman_environment.json"
          }

      # Upload exported data as artifact
      - name: Upload Exported Data
        uses: actions/upload-artifact@v4.6.0
        with:
          name: allocation-exported-data
          path: ${{ github.workspace }}/allocation_export
          retention-days: 7
